#!/usr/bin/env node
// Generates src/icons/registry.ts from the inline Font Awesome SVGs in the saved Zaapi pages,
// so the demo renders the exact glyphs (ADR 0001: identical icons, no icon library).
// Inputs stay git-ignored under "Original files/"; pass another location as the first argument
// (a worktree has no copy). Fails if the number of distinct icon names drifts from EXPECTED.
import { readFileSync, readdirSync, writeFileSync, statSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const EXPECTED = 106;
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const source = resolve(process.argv[2] ?? join(root, "Original files"));
const out = join(root, "src/icons/registry.ts");

function* htmlFiles(dir) {
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) yield* htmlFiles(p);
    else if (/\.html?$/i.test(entry)) yield p;
  }
}

const attr = (tag, name) => tag.match(new RegExp(`\\b${name}="([^"]*)"`))?.[1];

// registry[name][prefix] = { viewBox, paths }. The same name can ship in several styles
// (the rail shows far "bolt" when idle and fas "bolt" when active), so styles are kept apart.
const registry = {};
for (const file of [...htmlFiles(source)].sort()) {
  const html = readFileSync(file, "utf8");
  for (const m of html.matchAll(/<svg\b[^>]*\bdata-icon="[^"]+"[^>]*>[\s\S]*?<\/svg>/g)) {
    const svg = m[0];
    const open = svg.slice(0, svg.indexOf(">") + 1);
    const name = attr(open, "data-icon");
    const prefix = attr(open, "data-prefix") ?? "far";
    const viewBox = attr(open, "viewBox");
    const paths = [...svg.matchAll(/<path\b[^>]*>/g)].map(([p]) => {
      const opacity = attr(p, "opacity");
      return opacity === undefined ? { d: attr(p, "d") } : { d: attr(p, "d"), opacity: Number(opacity) };
    });
    if (!viewBox || paths.length === 0 || paths.some((p) => !p.d)) continue;
    registry[name] ??= {};
    registry[name][prefix] ??= { viewBox, paths };
  }
}

const names = Object.keys(registry).sort();
const glyphs = names.reduce((n, k) => n + Object.keys(registry[k]).length, 0);
console.log(`extract-icons: ${names.length} icon names, ${glyphs} glyphs (name x style) from ${source}`);
if (names.length !== EXPECTED) {
  console.error(`extract-icons: expected ${EXPECTED} icon names, found ${names.length}; refusing to write.`);
  process.exit(1);
}

const sorted = Object.fromEntries(
  names.map((n) => [n, Object.fromEntries(Object.keys(registry[n]).sort().map((p) => [p, registry[n][p]]))]),
);
writeFileSync(
  out,
  `// Generated by scripts/extract-icons.mjs from the saved Zaapi pages. Do not edit by hand.\n` +
    `// Font Awesome Pro glyphs as shipped in app.zaapi.com (see ADR 0001 for the licence caveat).\n` +
    `import type { IconRegistry } from "./types";\n\n` +
    `export const registry = ${JSON.stringify(sorted, null, 2)} as const satisfies IconRegistry;\n`,
);
console.log(`extract-icons: wrote ${out}`);
