#!/usr/bin/env node
// Generates src/icons/registry.ts from the inline Font Awesome SVGs in the saved Zaapi pages,
// so the demo renders the exact glyphs (ADR 0001: identical icons, no icon library).
// Inputs stay git-ignored under "Original files/"; pass another location as the first argument
// (a worktree has no copy). Fails if the number of distinct icon names drifts from EXPECTED.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const EXPECTED = 106;
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const source = resolve(process.argv[2] ?? join(root, "Original files"));
const out = join(root, "src/icons/registry.ts");

// Anchored on whitespace: a bare \b would let `opacity` match `fill-opacity` and `d` match `data-d`.
const attr = (tag, name) => tag.match(new RegExp(`\\s${name}="([^"]*)"`))?.[1];

// registry[name][prefix] = { viewBox, paths }. The same name can ship in several styles
// (the rail shows far "bolt" when idle and fas "bolt" when active), so styles are kept apart.
const registry = {};
const htmlFiles = readdirSync(source, { recursive: true, encoding: "utf8" }).filter((f) => /\.html?$/i.test(f));
for (const file of htmlFiles.sort().map((f) => join(source, f))) {
  const html = readFileSync(file, "utf8");
  for (const m of html.matchAll(/<svg\b[^>]*\bdata-icon="[^"]+"[^>]*>[\s\S]*?<\/svg>/g)) {
    const svg = m[0];
    const open = svg.slice(0, svg.indexOf(">") + 1);
    const name = attr(open, "data-icon");
    const prefix = attr(open, "data-prefix") ?? "far";
    const viewBox = attr(open, "viewBox");
    const paths = [...svg.matchAll(/<path\b[^>]*>/g)].map(([p]) => {
      const opacity = attr(p, "opacity");
      return opacity === undefined ? { d: attr(p, "d") } : { d: attr(p, "d"), opacity: Number(opacity) };
    });
    if (!viewBox || paths.length === 0 || paths.some((p) => !p.d)) continue;
    registry[name] ??= {};
    registry[name][prefix] ??= { viewBox, paths };
  }
}

// Glyphs the saved pages never rendered inline but the live app shows (found in the PR 7 fidelity
// pass). They come from the Font Awesome packs bundled in the saved pages' own JS files, as
// `{prefix:"far",iconName:"face-party",icon:[w,h,aliases,unicode,path]}`.
const FROM_BUNDLES = [
  ["arrow-down", "fal"],
  ["arrow-turn-down-left", "fal"],
  ["arrow-up", "fal"],
  ["bookmark", "fas"],
  ["comments", "fal"],
  ["comments", "far"],
  ["ellipsis-vertical", "fas"],
  ["face-party", "far"],
  ["users", "far"],
];
const htmlNames = Object.keys(registry).length;
const bundleFiles = readdirSync(source, { recursive: true, encoding: "utf8" }).filter((f) => /\.js$/i.test(f));
const bundles = bundleFiles.map((f) => readFileSync(join(source, f), "utf8"));
for (const [name, prefix] of FROM_BUNDLES) {
  if (registry[name]?.[prefix]) continue;
  const re = new RegExp(`\\{prefix:"${prefix}",iconName:"${name}",icon:\\[(\\d+),(\\d+),\\[[^\\]]*\\],"[^"]*",("(?:[^"\\\\]|\\\\.)*"|\\[[^\\]]*\\])\\]\\}`);
  const m = bundles.map((js) => js.match(re)).find(Boolean);
  if (!m) {
    console.error(`extract-icons: ${prefix} ${name} not found in the saved bundles; refusing to write.`);
    process.exit(1);
  }
  const d = JSON.parse(m[3]);
  registry[name] ??= {};
  registry[name][prefix] = { viewBox: `0 0 ${m[1]} ${m[2]}`, paths: (Array.isArray(d) ? d : [d]).map((x) => ({ d: x })) };
}

const names = Object.keys(registry).sort();
const glyphs = names.reduce((n, k) => n + Object.keys(registry[k]).length, 0);
console.log(`extract-icons: ${names.length} icon names, ${glyphs} glyphs (name x style) from ${source}`);
if (htmlNames !== EXPECTED) {
  console.error(`extract-icons: expected ${EXPECTED} icon names in the saved pages, found ${htmlNames}; refusing to write.`);
  process.exit(1);
}

const sorted = Object.fromEntries(
  names.map((n) => [n, Object.fromEntries(Object.keys(registry[n]).sort().map((p) => [p, registry[n][p]]))]),
);
writeFileSync(
  out,
  `// Generated by scripts/extract-icons.mjs from the saved Zaapi pages. Do not edit by hand.\n` +
    `// Font Awesome Pro glyphs as shipped in app.zaapi.com (see ADR 0001 for the licence caveat).\n` +
    `import type { IconRegistry } from "./types";\n\n` +
    `export const registry = ${JSON.stringify(sorted, null, 2)} as const satisfies IconRegistry;\n`,
);
console.log(`extract-icons: wrote ${out}`);
